Branding = "Default Theme"
Description = ""
Stylesheets = ["reset.css", "fonts.css", "layout.css", "theme-light.css", "proto.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
