stylesheets = [ "sizes.css", "theme-light.css", "roma.css", "responsive.css"]
rootstylesheets = [ "reset.css","fonts.css","layout.css" ]
PathName = ""

[Nav]
  HTML = ""
  File = ""

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
