Branding = ""
Description = ""
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
Stylesheets = ["sizes.css", "theme-light.css", "newsroom.css"]
PathName = ""

[Nav]
  HTML = ""
  File = ""

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
