Branding = "NewsMag"
Description = ""
RootStylesheets = ["reset.css", "fonts.css", "bind.css"]
Stylesheets = ["sizes.css", "theme-light.css", "home.css"]
PathName = ""
Version = "0.7.0"

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
