Branding = ""
Description = ""
RootStylesheets = ["reset.css", "fonts.css", "bind.css"]
Stylesheets = ["sizes.css", "theme-light.css", "pillar.css"]
PathName = ""
Version="1.2.3"
[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
