RootStylesheets = ["reset.css", "fonts.css", "layout.css", "theme-light.css", "marlow.css"]
Stylesheets = ["sizes.css", "theme-light.css", "marlow.css"]
PathName = ""

Description = "A bold, colorful theme that's eye-catching but also generally useful"
[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
