Branding = "Lanyon theme"
Description = "A theme that should look way too familiar to static blog uses"
Stylesheets = ["reset.css", "fonts.css", "layout.css", "skin.css", "lanyon.css"]
PathName = ""

[Nav]
  HTML = ""
  File = ""

[Header]
  HTML = ""
  File = ""

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = ""

[Sidebar]
  HTML = ""
  File = "sidebar.md"
