Branding = ""
Description = ""
RootStylesheets = ["fonts.css", "tufte.min.css", "layout.css"]
Stylesheets = ["theme-light.css", "responsive.css"]
PathName = ""

[Nav]
  HTML = ""
  File = ""

[Header]
  HTML = ""
  File = ""

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = ""

[Sidebar]
  HTML = ""
  File = ""
