Branding = "_"
Description = ""
Stylesheets = ["splendor.min.css"]
PathName = ""
[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = "<header><h3>Splendid</h3></header>"
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"


