Branding = "_"
Description = "The ur-theme, complete but stripped-down starting point"
#Stylesheets = ["sizes.css", "theme-light.css", "_.css", "responsive.css"]
Stylesheets = ["sizes.css", "theme-light.css", "_.css"]
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
