Branding = "empty"
Description = "Use to build themes from scratch"
Stylesheets = ["theme-light.css", "empty.css"]
RootStylesheets = ["reset.css", "fonts.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
