Name = "tom.im"
Branding = ""
Language = "en"
Theme = "tom.im"
Dir = "/Users/tom/code/tom.im"
AssetDir = ""
BaseDir = ""
Publish = "_pub"
ThemeDir = "/Users/tom/Library/Preferences/.d2/themes"
Ganalytics = "UA-152078779-2"

[company]
CompanyName = "tom.im"

[author]
FullName = "Tom Campbell"
