Branding = "_"
Description = ""
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
Stylesheets = ["sizes.css", "theme-light.css", "press-release.css"]
PathName = ""

[Header]
  HTML = ""
  File = "header.md"

[Navbar]
  HTML = ""
  File = ""

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = ""

[Sidebar]
  HTML = ""
  File = ""
